stages:
  - validate
  - build

default:
  image:
    name: maven:3-jdk-8-slim
    pull_policy: if-not-present
  cache:
    paths:
      - .m2/repository/
    when: always
  artifacts:
    expire_in: 36 hours
  tags:
    - whirl
  timeout: 3h

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'

checkstyle:
  stage: validate
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop' # Only run on merge requests to develop branch
      when: always
  allow_failure: true
  script:
    - mvn $MAVEN_OPTS checkstyle:checkstyle-aggregate checkstyle:check
  artifacts:
    paths:
      - target/site/*
    when: on_failure
    expire_in: 36 hours