build:
  nodes:
    builder:

      environment:
        sdkman:
          - java@8.0.302-open
          - maven
        apt_packages:
          - jq
        variables:
          _JAVA_OPTIONS: '-Xmx2048m' # Fixes error reproducible only in CI: [ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0.1:compile (default-compile) on project whirl-app-client: GWT exited with status 137 -> [Help 1]

      dependencies:
        override:
          - git submodule update --init --recursive

      project_setup:
        before:
          - TAG="v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" # get project version
        override:
          - mvn -pl . install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          - mvn -pl whirl-theme,whirl-selenium,whirl-codemirror install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          - command: mvn -P jdbc-postgresql,jdbc-oracle,jdbc-mysql -pl whirl-app,whirl-app/whirl-app-shared,whirl-app/whirl-app-client,whirl-app/whirl-app-server install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
            idle_timeout: 700
          - command: mvn -P jdbc-postgresql,jdbc-oracle,jdbc-mysql -pl whirl-editor,whirl-editor/whirl-editor-shared,whirl-editor/whirl-editor-client,whirl-editor/whirl-editor-server install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
            idle_timeout: 700

      tests:
        override:
          - mvn test

      deployment:
        - branch: master
          commands:
            - command: 'echo "Version: $TAG"'
              only_if: '[[ -z "$SCRUTINIZER_PR_NUMBER" ]]'
            - command: 'TAG=${TAG} bash ~/build/scripts/whirl/release-github.sh'
              only_if: '[[ -z "$SCRUTINIZER_PR_NUMBER" ]]'
            - command: 'TAG=${TAG} bash ~/build/scripts/whirl/release-docker.sh'
              only_if: '[[ -z "$SCRUTINIZER_PR_NUMBER" ]]'
            - command: 'TAG=${TAG} ENV_PREFIX=${JELASTIC_ENV_PREFIX} ENV_TYPE=${JELASTIC_ENV_DEMO} bash ~/build/scripts/whirl/deploy-jelastic-cli.sh'
              only_if: '$JELASTIC_ENABLED_DEMO && [[ -z "$SCRUTINIZER_PR_NUMBER" ]]'
              idle_timeout: 700
        - branch: develop
          commands:
            - command: 'ENV_PREFIX=${JELASTIC_ENV_PREFIX} ENV_TYPE=${JELASTIC_ENV_DEVELOP} bash ~/build/scripts/whirl/deploy-jelastic-maven.sh'
              only_if: '$JELASTIC_ENABLED_DEVELOP && [[ -z "$SCRUTINIZER_PR_NUMBER" ]]'
              idle_timeout: 700