build:
  nodes:
    builder:

      environment:
        sdkman:
          - java@8.0.302-open
          - maven
        apt_packages:
          - jq
        variables:
          _JAVA_OPTIONS: '-Xmx2048m' # Fixes error reproducible only in CI: [ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0.1:compile (default-compile) on project whirl-app-client: GWT exited with status 137 -> [Help 1]

      dependencies:
        override:
          - git submodule update --init --recursive

      project_setup:
        before:
          - TAG="v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" # get project version
        override:
          - mvn -pl . install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          - mvn -pl whirl-theme,whirl-selenium,whirl-codemirror install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          - command: mvn -P jdbc-postgresql -pl whirl-app,whirl-app/whirl-app-shared,whirl-app/whirl-app-client,whirl-app/whirl-app-server install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
            idle_timeout: 700
          - command: mvn -P jdbc-postgresql -pl whirl-editor,whirl-editor/whirl-editor-shared,whirl-editor/whirl-editor-client,whirl-editor/whirl-editor-server install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
            idle_timeout: 700

      tests:
        override:
          - mvn test

      deployment:
        - branch: '/^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/'
          commands:
            - command: bash ~/build/scripts/whirl/release-github.sh
        - branch: '/^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/'
          commands:
            - command: bash ~/build/scripts/whirl/deploy-jelastic-cli.sh
              only_if: $JELASTIC_ENABLED
              idle_timeout: 700