version: '3.7'

services:

  source:
    container_name: whirl
    profiles:
      - source
    build:
      context: ..
      dockerfile: docker/Source.Dockerfile # Download.Dockerfile uses prebuild WAR. To build from source change to Build.Dockerfile.
      target: all
    ports:
      - ${WHIRL_PORT:-8090}:8080
    volumes:
      - ${WHIRL_CONF:-./}conf/postgresql/context.xml.default:/usr/local/tomcat/conf/Catalina/localhost/context.xml.default # Tomcats global context configuration location.
      - ${WHIRL_WORK:-../.whirl-work}:/usr/local/whirl # Whirl applications location.
      - ${WHIRL_LOGS:-../target/docker/log}:/usr/local/tomcat/logs # Tomcats logs location
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql

  packaged:
    container_name: whirl
    profiles:
      - packaged
    build:
      context: ..
      dockerfile: docker/Packaged.Dockerfile # Download.Dockerfile uses prebuild WAR. To build from source change to Build.Dockerfile.
      target: all
    ports:
      - ${WHIRL_PORT:-8090}:8080
    volumes:
      - ${WHIRL_CONF:-./}conf/postgresql/context.xml.default:/usr/local/tomcat/conf/Catalina/localhost/context.xml.default # Tomcats global context configuration location.
      - ${WHIRL_WORK:-../.whirl-work}:/usr/local/whirl # Whirl applications location.
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql

  image:
    container_name: whirl
    profiles:
      - image
    image: otlichnosti/whirl:${TAG:-develop}
    ports:
      - ${WHIRL_PORT:-8090}:8080
    volumes:
      - ${WHIRL_CONF:-./}conf/postgresql/context.xml.default:/usr/local/tomcat/conf/Catalina/localhost/context.xml.default # Tomcats global context configuration location.
      - ${WHIRL_WORK:-../.whirl-work}:/usr/local/whirl # Whirl applications location.
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql

  postgresql:
    container_name: postgres
    image: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ${WHIRL_CONF:-./}db/postgresql/:/docker-entrypoint-initdb.d/ # Database initialisation scripts.
